FROM python:3.8

WORKDIR /opt/bin

RUN wget https://drive5.com/downloads/usearch11.0.667_i86linux32.gz
RUN gzip -d usearch11.0.667_i86linux32.gz && chmod +x usearch11.0.667_i86linux32

WORKDIR /tmp

COPY requirements.txt ./
RUN pip install -r requirements.txt

ENV BIN_LOCATION /opt/bin
ENV ASSETS_LOCATION /opt/files
ENV TEMP_ARTIFACTS_LOCATION /tmp/files

EXPOSE 5000

CMD ["python3", "main.py"]
