name: starpep-web-api-bio-dev

services:
  neo4j:
    image: code.moonstar-x.dev/webpep/neo4j-db:latest-arm
    restart: no
    ports:
      - 7687:7687
      - 7474:7474
    environment:
      TZ: America/Guayaquil
      NEO4J_AUTH: none

  cache:
    image: redis:7-alpine
    restart: no
    ports:
      - 6379:6379
    environment:
      TZ: America/Guayaquil

  queue:
    image: rabbitmq:3-management
    restart: no
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      TZ: America/Guayaquil
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: pass
